/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easyreport;

import easyreport.pdf.Style_Templates.OneTblStyle_ReportPDF;
import easyreport.excel.Style_Templates.Table_ExcelReport;
import easyreport.pdf.*;
import easyreport.objects.Cliente;

/**
 *
 * @author AHERNANDEZ
 */
public class tester {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        try {

            String JsonObjects = getJSONPrueba2();
            String[] encabezados3 = ("Código,Nombre,# Guías,Porcentaje COD,Pre autoriza,Autoriza,# Autorización,Total COD,Total Servicio,Total por acreditar,Razón social,Cuenta,Banco").split(",");
            String[] atributos3 = ("codigo,nombre,cantidadGuias,porcentajeCOD,usuarioPreAu,usuarioAu,autorizacion,totalCOD,totalServ,totalAcr,razonSocial,noCuenta,banco").split(",");
            TableReport tb3 = new TableReport(encabezados3, atributos3, JsonObjects, "Resumen de acreditación", "", "Resumen de acreditación sobre pagos recibidos por ");
            tb3.addOperation("totalCOD,totalServ,totalAcr");
            //Table_ExcelReport tbE = new Table_ExcelReport(tb3);
           // tbE.CrearRepote("C:\\Users\\AHERNANDEZ\\Desktop\\Json-Tests3", "ResumenAcr_Excel");
          //  tbE.AbrirReporte();
            String[] encTbl1 = ("Código,Porcentaje COD,Total COD,Total Servicio,Total por acreditar,Razón social,Cuenta,Banco,Autoriza,# Autorización").split(",");
            String[] atrTbl1 = ("codigo,porcentajeCOD,totalCOD,totalServ,totalAcr,razonSocial,noCuenta,banco,usuarioAu,autorizacion").split(",");
            TableReport pdfTbl1 = new TableReport(encTbl1, atrTbl1, JsonObjects, "Resumen de autorización para acreditaciones COD", "Detalles");
            pdfTbl1.addOperation("totalCOD,totalServ,totalAcr");
            OneTblStyle_ReportPDF tr = new OneTblStyle_ReportPDF("C:\\TEMPORAL\\ReportesSACOD", "ResumenAUT");
            tr.create(pdfTbl1);
            tr.AbrirArchivo();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public static String getJSONPrueba2() {
        return "[\n"
                + "    {\n"
                + "        \"fechaIni\": \"22/10/2020\",\n"
                + "        \"fechaFin\": \"22/10/2020\",\n"
                + "        \"codigo\": \"COD0000\",\n"
                + "        \"nombre\": \"PRUEBAS COD GUATEX0\",\n"
                + "        \"acreditado\": \"NO\",\n"
                + "        \"cantidadGuias\": \"1\",\n"
                + "        \"razonSocial\": \"CONSUMIDOR FINAL\",\n"
                + "        \"totalCOD\": \"811.0000\",\n"
                + "        \"totalServ\": \"32.4400\",\n"
                + "        \"totalAcr\": \"778.5600\",\n"
                + "        \"usuarioPreAu\": \"GFIGUEROA\",\n"
                + "        \"usuarioAu\": \"GFIGUEROA\",\n"
                + "        \"autorizacion\": \"COD0003-5\",\n"
                + "        \"noCuenta\": \"101-002718-9\",\n"
                + "        \"porcentajeCOD\": \"4.00\",\n"
                + "        \"banco\": \"INDUSTRIAL\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"fechaIni\": \"22/10/2020\",\n"
                + "        \"fechaFin\": \"22/10/2020\",\n"
                + "        \"codigo\": \"COD0001\",\n"
                + "        \"nombre\": \"PRUEBAS COD GUATEX1\",\n"
                + "        \"acreditado\": \"NO\",\n"
                + "        \"cantidadGuias\": \"3\",\n"
                + "        \"razonSocial\": \"INVERSIONES INTERNACIONALES J & R, SOCIEDAD ANONIMA\",\n"
                + "        \"totalCOD\": \"700.0000\",\n"
                + "        \"totalServ\": \"28.0000\",\n"
                + "        \"totalAcr\": \"672.0000\",\n"
                + "        \"usuarioPreAu\": \"GFIGUEROA\",\n"
                + "        \"usuarioAu\": \"GFIGUEROA\",\n"
                + "        \"autorizacion\": \"COD0003-5\",\n"
                + "        \"noCuenta\": \"104-001258-5\",\n"
                + "        \"porcentajeCOD\": \"4.00\",\n"
                + "        \"banco\": \"INDUSTRIAL\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"fechaIni\": \"22/10/2020\",\n"
                + "        \"fechaFin\": \"22/10/2020\",\n"
                + "        \"codigo\": \"COD0002\",\n"
                + "        \"nombre\": \"PRUEBAS COD GUATEX2\",\n"
                + "        \"acreditado\": \"NO\",\n"
                + "        \"cantidadGuias\": \"1\",\n"
                + "        \"razonSocial\": \"CONSUMIDOR FINAL\",\n"
                + "        \"totalCOD\": \"750.0000\",\n"
                + "        \"totalServ\": \"30.0000\",\n"
                + "        \"totalAcr\": \"720.0000\",\n"
                + "        \"usuarioPreAu\": \"GFIGUEROA\",\n"
                + "        \"usuarioAu\": \"GFIGUEROA\",\n"
                + "        \"autorizacion\": \"COD0003-5\",\n"
                + "        \"noCuenta\": \"101-001018-9\",\n"
                + "        \"porcentajeCOD\": \"4.00\",\n"
                + "        \"banco\": \"INDUSTRIAL\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"fechaIni\": \"22/10/2020\",\n"
                + "        \"fechaFin\": \"22/10/2020\",\n"
                + "        \"codigo\": \"COD0003\",\n"
                + "        \"nombre\": \"PRUEBAS COD GUATEX3\",\n"
                + "        \"acreditado\": \"NO\",\n"
                + "        \"cantidadGuias\": \"5\",\n"
                + "        \"razonSocial\": \"LOGICOM DE GUATEMALA SOCIEDAD ANONIMA\",\n"
                + "        \"totalCOD\": \"650.0000\",\n"
                + "        \"totalServ\": \"26.0000\",\n"
                + "        \"totalAcr\": \"624.0000\",\n"
                + "        \"usuarioPreAu\": \"GFIGUEROA\",\n"
                + "        \"usuarioAu\": \"GFIGUEROA\",\n"
                + "        \"autorizacion\": \"COD0003-5\",\n"
                + "        \"noCuenta\": \"111-005218-5\",\n"
                + "        \"porcentajeCOD\": \"4.00\",\n"
                + "        \"banco\": \"INDUSTRIAL\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"fechaIni\": \"22/10/2020\",\n"
                + "        \"fechaFin\": \"22/10/2020\",\n"
                + "        \"codigo\": \"COD0004\",\n"
                + "        \"nombre\": \"PRUEBAS COD GUATEX4\",\n"
                + "        \"acreditado\": \"NO\",\n"
                + "        \"cantidadGuias\": \"2\",\n"
                + "        \"razonSocial\": \"UNION ABARROTERA, S.A.\",\n"
                + "        \"totalCOD\": \"600.0000\",\n"
                + "        \"totalServ\": \"24.0000\",\n"
                + "        \"totalAcr\": \"576.0000\",\n"
                + "        \"usuarioPreAu\": \"GFIGUEROA\",\n"
                + "        \"usuarioAu\": \"GFIGUEROA\",\n"
                + "        \"autorizacion\": \"COD0003-5\",\n"
                + "        \"noCuenta\": \"105-002718-9\",\n"
                + "        \"porcentajeCOD\": \"4.00\",\n"
                + "        \"banco\": \"INDUSTRIAL\"\n"
                + "    },\n"
                + "]";
    }

    public static String getJSONPrueba() {
        return "[\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"1007.00\",\n"
                + "        \"codcob\": \"0000000\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200018\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"TECñññ\",\n"
                + "        \"dirrem1\": \"MZ. C CASA NO. 49 ZONA 17\",\n"
                + "        \"telrem\": \"5874-5378\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"0000000\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200017\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DISTRIBUIDORA GONGAI\",\n"
                + "        \"dirrem1\": \"2 CALLE 6-56 ZONA 2 MIXCO COL. SANTA RITA 1\",\n"
                + "        \"telrem\": \"3283-6203\",\n"
                + "        \"nomdes\": \"REPUESTOS TONY\",\n"
                + "        \"dirdes1\": \"16 CALLE 12-15 ZONA 12\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"4049-6617 5624-6770\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"0000000\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200020\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"LA BANANA BOX\",\n"
                + "        \"dirrem1\": \"C.C. PLAZA MEDICA DEL NORTE, LOCAL 26 KM. 7.5\",\n"
                + "        \"telrem\": \"2257-12146 4276-7177\",\n"
                + "        \"nomdes\": \"DE LA PEÑA GRAMAJO CONSULTORIA (PETIT)\",\n"
                + "        \"dirdes1\": \"6A. AV. 10-70 ZONA 17, RESIDENCIALES DEL NORTE\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2258-1404\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"0000000\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200021\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"TECNIVET\",\n"
                + "        \"dirrem1\": \"MZ. C CASA NO. 49 ZONA 17\",\n"
                + "        \"telrem\": \"5874-5378\",\n"
                + "        \"nomdes\": \"LA BANANA BOX\",\n"
                + "        \"dirdes1\": \"C.C. PLAZA MEDICA DEL NORTE, LOCAL 26 KM. 7.5\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2257-12146 4276-7177\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"CHM\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"0000000\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200022\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"TECNIVET\",\n"
                + "        \"dirrem1\": \"MZ. C CASA NO. 49 ZONA 17\",\n"
                + "        \"telrem\": \"5874-5378\",\n"
                + "        \"nomdes\": \"LA BANANA BOX\",\n"
                + "        \"dirdes1\": \"C.C. PLAZA MEDICA DEL NORTE, LOCAL 26 KM. 7.5\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2257-12146 4276-7177\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"CHM\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"0000000\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200025\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DE LA PEÑA GRAMAJO CONSULTORIA (PETIT)\",\n"
                + "        \"dirrem1\": \"6A. AV. 10-70 ZONA 17, RESIDENCIALES DEL NORTE\",\n"
                + "        \"telrem\": \"2258-1404\",\n"
                + "        \"nomdes\": \"LA BANANA BOX\",\n"
                + "        \"dirdes1\": \"C.C. PLAZA MEDICA DEL NORTE, LOCAL 26 KM. 7.5\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2257-12146 4276-7177\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"CHM\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"0000000\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200026\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"LA BANANA BOX\",\n"
                + "        \"dirrem1\": \"C.C. PLAZA MEDICA DEL NORTE, LOCAL 26 KM. 7.5\",\n"
                + "        \"telrem\": \"2257-12146 4276-7177\",\n"
                + "        \"nomdes\": \"GROUPEX FINANCIAL, S.A.\",\n"
                + "        \"dirdes1\": \"CIUDAD\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"5709-3535\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"ANT\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"0000000\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200027\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"LA BANANA BOX\",\n"
                + "        \"dirrem1\": \"C.C. PLAZA MEDICA DEL NORTE, LOCAL 26 KM. 7.5\",\n"
                + "        \"telrem\": \"2257-12146 4276-7177\",\n"
                + "        \"nomdes\": \"GROUPEX FINANCIAL, S.A.\",\n"
                + "        \"dirdes1\": \"CIUDAD\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"5709-3535\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"ANT\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"0000000\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200007\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"ANTONIO HERNANDEZ\",\n"
                + "        \"dirrem1\": \"CIUDAD GUATEMALA\",\n"
                + "        \"telrem\": \"32233232\",\n"
                + "        \"nomdes\": \"KARLA ORTIZ\",\n"
                + "        \"dirdes1\": \"VILLA NUEVA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"32323232\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUA\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"0000000\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200011\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"CÉSAR NUÑEZ ÑÑÑ*-/!\\\"#$%&/()\",\n"
                + "        \"dirrem1\": \"PRUEBA ÑÑÑ*-/!\\\"#$%&/()\",\n"
                + "        \"telrem\": \"23323232\",\n"
                + "        \"nomdes\": \"HERNÁNDEZ PEDOR ÑÑÑ*-/!\\\"#$%&/()\",\n"
                + "        \"dirdes1\": \"CIUDAD ÑÑÑ*-/!\\\"#$%&/()\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"32323232\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"CAP\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200012\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"LA BANANA BOX\",\n"
                + "        \"dirdes1\": \"C.C. PLAZA MEDICA DEL NORTE, LOCAL 26 KM. 7.5\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2257-12146 4276-7177\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUA\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200009\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"TECNIVET\",\n"
                + "        \"dirrem1\": \"MZ. C CASA NO. 49 ZONA 17\",\n"
                + "        \"telrem\": \"5874-5378\",\n"
                + "        \"nomdes\": \"LA BANANA BOX\",\n"
                + "        \"dirdes1\": \"C.C. PLAZA MEDICA DEL NORTE, LOCAL 26 KM. 7.5\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2257-12146 4276-7177\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"CHM\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200000\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"LA BANANA BOX\",\n"
                + "        \"dirrem1\": \"C.C. PLAZA MEDICA DEL NORTE, LOCAL 26 KM. 7.5\",\n"
                + "        \"telrem\": \"2257-12146 4276-7177\",\n"
                + "        \"nomdes\": \"CANELLA\",\n"
                + "        \"dirdes1\": \"7 AVENIDA 8-65 ZONA 4\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2338-5900 2334-8299\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"TOT\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"cod_VALORACOBRAR\": \"17.00\",\n"
                + "        \"codcob\": \"CONTADO\",\n"
                + "        \"fecha\": \"2020-06-02\",\n"
                + "        \"noguia\": \"T2406200002\",\n"
                + "        \"cod_SEGURO\": \"\",\n"
                + "        \"cod_RECIBO\": \"\",\n"
                + "        \"nomrem\": \"DROGUERIA C'AYALA\",\n"
                + "        \"dirrem1\": \"13 AV. 19-14 ZONA 2, RESIDENCIALES EL ROBLE\",\n"
                + "        \"telrem\": \"5749-2517 4083-1499\",\n"
                + "        \"nomdes\": \"HAIFA FASHION\",\n"
                + "        \"dirdes1\": \"19 CALLE 3-18 ZONA 1, GUATEMALA\",\n"
                + "        \"p_RECIBIO\": \"\",\n"
                + "        \"horapod\": \"\",\n"
                + "        \"teldes\": \"2221-1028 2238-1888\",\n"
                + "        \"ptoori\": \"CAP\",\n"
                + "        \"ptodes\": \"GUS\",\n"
                + "        \"llavecliente\": \"\"\n"
                + "    },\n"
                + "]".trim();
    }
}
